import Foundation
import SwiftUI

enum L10n {
    static var language: String {
        get { UserDefaults.standard.string(forKey: "language") ?? (Locale.current.language.languageCode?.identifier == "zh" ? "zh" : "en") }
        set { UserDefaults.standard.set(newValue, forKey: "language") }
    }

    private static let en: [String: String] = [
        "app.name": "MSL FileManager",
        "sidebar.favorites": "Favorites",
        "sidebar.linux_vm": "Linux VM",
        "sidebar.no_disks": "No external disks",
        "sidebar.vm_status": "VM",
        "tab.new_tab": "New Tab",
        "tab.home": "Home",
        "browser.no_items": "No Items",
        "browser.empty_folder": "This folder is empty",
        "browser.no_selection": "No Selection",
        "browser.select_file_preview": "Select a file to preview",
        "browser.folder": "Folder",
        "browser.linux_vm": "Linux VM",
        "column.name": "Name",
        "column.size": "Size",
        "column.date": "Date Modified",
        "column.kind": "Kind",
        "toolbar.sort": "Sort",
        "toolbar.show_hidden": "Show Hidden Files",
        "toolbar.preview": "Preview",
        "context.open": "Open",
        "context.open_with": "Open With...",
        "context.copy": "Copy",
        "context.paste": "Paste",
        "context.move_to_trash": "Move to Trash",
        "context.get_info": "Get Info",
        "context.new_folder": "New Folder",
        "context.extract_here": "Extract Here",
        "context.extract_to": "Extract to...",
        "context.view_contents": "View Package Contents",
        "archive.preview": "Archive Preview",
        "archive.extract_all": "Extract All",
        "archive.extract_selected": "Extract Selected",
        "archive.extract_to": "Extract to...",
        "archive.no_archive": "Not an archive file",
        "archive.contents": "Contents",
        "archive.size": "Size",
        "archive.compressed": "Compressed",
        "archive.uncompressed": "Uncompressed",
        "settings.general": "General",
        "settings.vm": "Virtual Machine",
        "settings.ai": "AI Assistant",
        "settings.language": "Language",
        "settings.hidden_files": "Show hidden files by default",
        "settings.view_mode": "Default view mode",
        "settings.vm_status": "VM Status",
        "settings.start_vm": "Start VM",
        "settings.stop_vm": "Stop VM",
        "settings.restart_vm": "Restart VM",
        "settings.cpus": "CPUs",
        "settings.memory": "Memory",
        "settings.disk": "Disk",
        "settings.ai_enable": "Enable AI Assistant",
        "settings.ai_provider": "Provider",
        "settings.ai_key": "API Key",
        "disk.manager": "Disk Manager",
        "disk.no_disks": "No External Disks",
        "disk.connect": "Connect an external disk",
        "disk.mount_all": "Mount All",
        "disk.unmount_all": "Unmount All",
        "disk.mount_selected": "Mount Selected",
        "disk.mounted": "Mounted",
        "disk.unmounted": "Not Mounted",
        "ai.title": "AI Assistant",
        "ai.placeholder": "Ask AI...",
    ]

    private static let zh: [String: String] = [
        "app.name": "MSL 文件管理器",
        "sidebar.favorites": "收藏夹",
        "sidebar.linux_vm": "Linux 虚拟机",
        "sidebar.no_disks": "无外部磁盘",
        "sidebar.vm_status": "虚拟机",
        "tab.new_tab": "新建标签",
        "tab.home": "个人目录",
        "browser.no_items": "无项目",
        "browser.empty_folder": "此文件夹为空",
        "browser.no_selection": "未选择",
        "browser.select_file_preview": "选择文件以预览",
        "browser.folder": "文件夹",
        "browser.linux_vm": "Linux 虚拟机",
        "column.name": "名称",
        "column.size": "大小",
        "column.date": "修改日期",
        "column.kind": "类型",
        "toolbar.sort": "排序",
        "toolbar.show_hidden": "显示隐藏文件",
        "toolbar.preview": "预览",
        "context.open": "打开",
        "context.open_with": "打开方式...",
        "context.copy": "复制",
        "context.paste": "粘贴",
        "context.move_to_trash": "移到废纸篓",
        "context.get_info": "显示简介",
        "context.new_folder": "新建文件夹",
        "context.extract_here": "在此解压",
        "context.extract_to": "解压到...",
        "context.view_contents": "显示包内容",
        "archive.preview": "压缩包预览",
        "archive.extract_all": "全部解压",
        "archive.extract_selected": "解压所选",
        "archive.extract_to": "解压到...",
        "archive.no_archive": "不是压缩文件",
        "archive.contents": "内容",
        "archive.size": "大小",
        "archive.compressed": "压缩后",
        "archive.uncompressed": "解压后",
        "settings.general": "通用",
        "settings.vm": "虚拟机",
        "settings.ai": "AI 助手",
        "settings.language": "语言",
        "settings.hidden_files": "默认显示隐藏文件",
        "settings.view_mode": "默认视图模式",
        "settings.vm_status": "虚拟机状态",
        "settings.start_vm": "启动虚拟机",
        "settings.stop_vm": "停止虚拟机",
        "settings.restart_vm": "重启虚拟机",
        "settings.cpus": "处理器",
        "settings.memory": "内存",
        "settings.disk": "磁盘",
        "settings.ai_enable": "启用 AI 助手",
        "settings.ai_provider": "提供商",
        "settings.ai_key": "API 密钥",
        "disk.manager": "磁盘管理",
        "disk.no_disks": "无外部磁盘",
        "disk.connect": "连接外部磁盘",
        "disk.mount_all": "全部挂载",
        "disk.unmount_all": "全部卸载",
        "disk.mount_selected": "挂载所选",
        "disk.mounted": "已挂载",
        "disk.unmounted": "未挂载",
        "ai.title": "AI 助手",
        "ai.placeholder": "向 AI 提问...",
    ]

    static func t(_ key: String) -> String {
        language == "zh" ? (zh[key] ?? en[key] ?? key) : (en[key] ?? key)
    }
}

extension String {
    var localized: String { L10n.t(self) }
}
